### ISSUE TITLE
Download the training/evaluation data

### ISSUE THREAD

**Issue by ypw-lbj** [jongwooko/distillm#10]
How can I download the training/evaluation intruction-response data? 
Can you tell me how to download the data? I tried but failed.

link: 
https://conversationhub.blob.core.windows.net/beit-share-public/MiniLLM/data.tar?sv=2021-10-04&st=2023-06-08T11%3A16%3A02Z&se=2033-06-09T11%3A16%3A00Z&sr=c&sp=r&sig=N4pfCVmSeq4L4tS8QbrFVsX6f6q844eft8xSuXdxU48%3D

Thank you.

**Comment by ypw-lbj** [comment]
I used Azure Storage Explorer to download data, but it showed that there was no data available.

**Comment by jongwooko** [comment]
hi @ypw-lbj, I recently checked that the link is not working. Instead, the authors of MiniLLM provide the new instruction for downloading the processed dataset. You can check the section 2.1 in this link: https://github.com/microsoft/LMOps/blob/main/minillm/README.md

I will update this part on our repository, too. thanks for your interesting.
