### ISSUE TITLE
Dataset link seems invalid now

### ISSUE THREAD

**Issue by aaab8b** [jongwooko/distillm#12]
Thanks for the wonderful work! However, the dataset link seems invalid right now. can you guys provide another way to reach for the data?

**Comment by jongwooko** [comment]
hi @aaab8b , I recently checked that the link is not working. Instead, the authors of MiniLLM provide the new instruction for downloading the processed dataset. You can check the section 2.1 in this link: https://github.com/microsoft/LMOps/blob/main/minillm/README.md

Sorry for this issue. I will fix it soon. Thanks for your interesting.

**Comment by jongwooko** [comment]
I will close issue, and let you know once I update it.
