### ISSUE TITLE
The metric of GPT-4 Eval

### ISSUE THREAD

**Issue by liuxy1103** [jongwooko/distillm#2]
How is GPT-4 Eval calculated? Can you provide the following assessment codes in addition to rouge-L?

**Comment by jongwooko** [comment]
Hi. Thank you for showing interest in our work.

The baseline code for our GPT-4 evaluation is available at https://github.com/raymin0223/fast_robust_early_exit/tree/main/gpt_eval.

We will make our customized evaluation code available as soon as possible.
