### ISSUE TITLE
How to download the models after sft 

### ISSUE THREAD

**Issue by liuxy1103** [jongwooko/distillm#3]
how to download the baselines and DistiLLM models based on fine-tuned models. could you mind providing these models like minillm

**Comment by jongwooko** [comment]
Hi, thank you for your interest in our work.

We plan to release our DistiLLM models, which are based on our fine-tuning code, soon.

Please continue to follow our progress.

**Comment by liuxy1103** [comment]
Thanks! I find "evaluate_exposure_bias " in evaluate.py  is not available

**Comment by jongwooko** [comment]
Thanks again for your comments. 

_evaluation_exposure_bias_ is redundant function as our code is based on MiniLLM, but we do not use it in our works.

We will remove such redundant code for next updating. Thank you :)

**Comment by liuxy1103** [comment]
I get it, thanks for your patience
